# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - cicd

jobs:
  push_to_registry_deploy_to_k8s:
    name: Push Docker image to Docker Hub and Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Define Docker tag
        id: define-tag
        run: echo "DOCKER_TAG=steveandroulakis/temporal-money-transfer-java-worker:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: steveandroulakis/temporal-money-transfer-java-worker
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v2.0
      - name: set kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_API }}
          k8s-secret: ${{ secrets.SA_TOKEN }}
        id: setcontext

      - uses: Azure/k8s-deploy@v5
        with:
          namespace: 'stevea-worker-as-a-service'
          images: ${{ env.DOCKER_TAG }}
          action: deploy
          strategy: basic
          manifests: |
              yaml/deployment.yaml
          force: true